### ISSUE TITLE
Create the App #1

### ISSUE THREAD

**Issue by CitizenYY** [CitizenYY/THP2-back#2]
### Why ?

Creating the app, "_the right way_" will help the process as changing the default after is a bit tedious/difficult in rails.

### Must have:
- [ ] Postgresql
- [ ] No front
- [ ] No Tests framework

### Todo
- [ ] Read through the `rails new --help` documentation
- [ ] Create the app

##### What is rails api mode
- [ ] http://guides.rubyonrails.org/api_app.html
##### What is a middleware
  - [ ] http://railscasts.com/episodes/151-rack-middleware
  - [ ] http://guides.rubyonrails.org/rails_on_rack.html#action-dispatcher-middleware-stack

**Comment by CitizenYY** [comment]
Je me souviens plus du process, faut bien créer une branche par ticket.. PR... puis merge ? c'est bien ça @denispasin ?

**Comment by denispasin** [comment]
Yep !
